apiVersion: v1
kind: Service
metadata:
  name: {{ include "diomika.fullname" . }}
  labels:
    {{- include "diomika.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "diomika.selectorLabels" . | nindent 4 }}
