"""CQRS handlers integration for real endpoints."""
import logging
import uuid
from datetime import datetime
from typing import Optional, Dict, Any, Type, Generic, TypeVar
from abc import ABC, abstractmethod

from core.cqrs import Command, Query, CommandBus, QueryBus, CommandHandler, QueryHandler
from core.outbox_pattern import OutboxPublisher
from core.audit_trail import AuditTrail

logger = logging.getLogger("diomika-api")

T = TypeVar("T")
R = TypeVar("R")


class HandlerRegistry:
    """Registry for command and query handlers."""

    def __init__(self):
        self.command_handlers: Dict[Type[Command], CommandHandler] = {}
        self.query_handlers: Dict[Type[Query], QueryHandler] = {}
        self.command_bus: Optional[CommandBus] = None
        self.query_bus: Optional[QueryBus] = None
        self.outbox_publisher: Optional[OutboxPublisher] = None

    def register_command_handler(self, command_type: Type[Command], handler: CommandHandler):
        """Register a command handler."""
        self.command_handlers[command_type] = handler
        if self.command_bus:
            self.command_bus.register_handler(command_type, handler)
        logger.debug(f"Registered command handler for {command_type.__name__}")

    def register_query_handler(self, query_type: Type[Query], handler: QueryHandler):
        """Register a query handler."""
        self.query_handlers[query_type] = handler
        if self.query_bus:
            self.query_bus.register_handler(query_type, handler)
        logger.debug(f"Registered query handler for {query_type.__name__}")

    def initialize_buses(self, command_bus: CommandBus, query_bus: QueryBus):
        """Initialize buses and register all handlers."""
        self.command_bus = command_bus
        self.query_bus = query_bus

        for cmd_type, handler in self.command_handlers.items():
            command_bus.register_handler(cmd_type, handler)

        for query_type, handler in self.query_handlers.items():
            query_bus.register_handler(query_type, handler)

        logger.info(
            f"Initialized buses with {len(self.command_handlers)} command handlers "
            f"and {len(self.query_handlers)} query handlers"
        )

    def set_outbox_publisher(self, publisher: OutboxPublisher):
        """Set outbox publisher for event publishing."""
        self.outbox_publisher = publisher


class EndpointCommandHandler(CommandHandler[Command, Dict[str, Any]], ABC):
    """Base handler for endpoint commands."""

    def __init__(self, registry: Optional[HandlerRegistry] = None):
        self.registry = registry
        self.audit_trail = AuditTrail()

    async def handle(self, command: Command) -> Dict[str, Any]:
        """Handle command with audit trail."""
        command_id = command.command_id or str(uuid.uuid4())
        command.command_id = command_id

        try:
            # Log command in audit trail
            self.audit_trail.log_command(
                command_id=command_id,
                command_type=type(command).__name__,
                user_id=command.user_id,
                request_id=command.request_id,
                data=self._extract_command_data(command),
            )

            # Execute handler
            result = await self._execute(command)

            # Publish events via outbox
            if self.registry and self.registry.outbox_publisher:
                await self._publish_events(command, result)

            return {
                "success": True,
                "command_id": command_id,
                "result": result,
                "timestamp": datetime.utcnow().isoformat(),
            }

        except Exception as e:
            logger.error(f"Command {command_id} failed: {e}")
            self.audit_trail.log_error(command_id, str(e))
            raise

    @abstractmethod
    async def _execute(self, command: Command) -> Dict[str, Any]:
        """Execute the command. Must be implemented by subclasses."""
        pass

    async def _publish_events(self, command: Command, result: Dict[str, Any]):
        """Publish events generated by command to outbox."""
        events = self._get_generated_events(command, result)
        for event in events:
            await self.registry.outbox_publisher.publish_event(
                aggregate_id=event.get("aggregate_id"),
                event_type=event.get("event_type"),
                data=event.get("data"),
                user_id=command.user_id,
                request_id=command.request_id,
            )

    def _extract_command_data(self, command: Command) -> Dict[str, Any]:
        """Extract relevant data from command for logging."""
        return {
            key: value
            for key, value in vars(command).items()
            if not key.startswith("_") and key != "metadata"
        }

    def _get_generated_events(self, command: Command, result: Dict[str, Any]) -> list:
        """Get events generated by command execution."""
        # Can be overridden by subclasses to emit specific events
        return []


class EndpointQueryHandler(QueryHandler[Query, Dict[str, Any]], ABC):
    """Base handler for endpoint queries."""

    def __init__(self):
        self.audit_trail = AuditTrail()

    async def handle(self, query: Query) -> Dict[str, Any]:
        """Handle query with audit trail."""
        query_id = query.query_id or str(uuid.uuid4())
        query.query_id = query_id

        try:
            # Log query in audit trail
            self.audit_trail.log_query(
                query_id=query_id,
                query_type=type(query).__name__,
                user_id=query.user_id,
                request_id=query.request_id,
            )

            # Execute handler
            result = await self._execute(query)

            return {
                "success": True,
                "query_id": query_id,
                "result": result,
                "timestamp": datetime.utcnow().isoformat(),
            }

        except Exception as e:
            logger.error(f"Query {query_id} failed: {e}")
            self.audit_trail.log_error(query_id, str(e))
            raise

    @abstractmethod
    async def _execute(self, query: Query) -> Dict[str, Any]:
        """Execute the query. Must be implemented by subclasses."""
        pass


class CQRSMiddleware:
    """Middleware for CQRS integration."""

    def __init__(self, registry: HandlerRegistry):
        self.registry = registry

    async def __call__(self, request):
        """Attach handler registry to request."""
        request.state.handler_registry = self.registry
        return request


class CommandResult(Generic[T]):
    """Result of command execution."""

    def __init__(self, success: bool, data: Optional[T] = None, error: Optional[str] = None):
        self.success = success
        self.data = data
        self.error = error
        self.timestamp = datetime.utcnow()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "data": self.data,
            "error": self.error,
            "timestamp": self.timestamp.isoformat(),
        }


# Global registry
_handler_registry: Optional[HandlerRegistry] = None


def get_handler_registry() -> HandlerRegistry:
    """Get global handler registry."""
    global _handler_registry
    if _handler_registry is None:
        _handler_registry = HandlerRegistry()
    return _handler_registry


def initialize_cqrs(command_bus: CommandBus, query_bus: QueryBus):
    """Initialize CQRS with buses."""
    registry = get_handler_registry()
    registry.initialize_buses(command_bus, query_bus)
    return registry
